AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template
Parameters:
  Ami:
    Description: Ami image for my instance
    Type: String
    Default: ami-1718281
Resources:
  MyEC2Instance: #An inline comment
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: !Ref Ami
      InstanceType: t1.micro
      KeyName: testkey
      BlockDeviceMappings:
        -
          DeviceName: /dev/sdm
          Ebs:
            VolumeType: gp2
            DeleteOnTermination: false
            VolumeSize: 8
Outputs:
  MyOutput:
    Description: This is an output of instance ID
    Value: !Ref MyEC2Instance
    Export:
      Name: MyEC2InstanceID
